import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Search from "./Components/Search";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="bg-slate-200">
                <Search />
                {children}
            </body>
        </html>
    );
}
